# Подготовка исходных данных к анализу

In [1]:
import pandas as pd

In [2]:
texts_df = pd.read_parquet("../data/raw/text.parquet")
metrics_df = pd.read_parquet("../data/raw/metrics.parquet")
df = pd.concat([texts_df, metrics_df], axis=1)

In [3]:
df.head()

,age,user_id,gender,text,source_url,text__symbols_length,text__sentences_count,text__long_sentences_proportion,text__unpopular_words_proportion,text__obscene_proportion,...,punct__mean_usage_>,pos__mean_usage_INTJ,punct__mean_usage_/,punct__mean_usage_*,punct__mean_usage__,punct__mean_usage_~,entities__mean_usage_TAG,entities__mean_usage_EMAIL,entities__mean_usage_PHONE,entities__mean_usage_POINTER
0,16,968,мужской,Поход в sex shop. У моей подруги (не девушки) ...,NaN,113.750000,12,0.666667,0.363636,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16,968,мужской,"AD&D забавы! Все, кто играл в игры с системой ...",NaN,52.925926,27,0.666667,0.378676,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16,969,мужской,Один день гимназии. Первое место на школьном и...,NaN,63.956522,23,0.695652,0.334559,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16,969,мужской,Без двух дней 200 месяцев. Сегодня был окружн...,NaN,76.733333,15,0.666667,0.370558,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16,969,мужской,"История с нами. Что же, если бы вы жили веком ...",NaN,93.400000,15,0.800000,0.269231,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
start_size = len(df)

In [5]:
is_dublicate = df.text.duplicated()
df = df[~is_dublicate]

In [6]:
df['length'] = df['text'].apply(len)

In [7]:
df.columns

Index(['age', 'user_id', 'gender', 'text', 'source_url',
       'text__symbols_length', 'text__sentences_count',
       'text__long_sentences_proportion', 'text__unpopular_words_proportion',
       'text__obscene_proportion', 'text__rare_words_proportion',
       'text__type_token_ratio', 'text__normalized_shannon_entropy',
       'text__mean_words_length', 'text__long_words_proportion',
       'text__lexicon_size', 'text__lexical_diversity_per_sentence',
       'entities__mean_usage_QUOTE', 'entities__mean_usage_NUMBER',
       'entities__mean_usage_MEAS', 'entities__mean_usage_ENUM',
       'entities__mean_usage_FOREIGN', 'entities__breadth_of_use_entities',
       'pos__index_of_formality', 'pos__breadth_of_use_pos',
       'pos__pair_of_adv_per_sentence', 'pos__mean_usage_NOUN',
       'pos__mean_usage_PRON', 'pos__mean_usage_ADV', 'pos__mean_usage_ADP',
       'pos__mean_usage_ADJ', 'pos__mean_usage_SCONJ', 'pos__mean_usage_AUX',
       'pos__mean_usage_CCONJ', 'pos__mean_usage_VERB',
       'pos__mean_usage_PROPN', 'pos__mean_usage_DET', 'pos__mean_usage_PART',
       'pos__('ADJ-Pos', 'NOUN')', 'pos__('PROPN', 'PUNCT')',
       'pos__('PUNCT', 'SCONJ')', 'pos__('ADP', 'ADJ-Pos')',
       'pos__('ADP', 'PRON')', 'pos__('PUNCT', 'ADV')',
       'pos__('PUNCT', 'PRON')', 'pos__('ADJ-Pos', 'PUNCT')',
       'pos__('PUNCT', 'CCONJ')', 'pos__index_of_formality_tuldava',
       'pos__index_of_formality_heylinger', 'punct__breadth_of_use_puncts',
       'punct__mean_usage_:', 'punct__mean_usage_"', 'punct__mean_usage_.',
       'punct__mean_usage_?', 'punct__mean_usage_(', 'punct__mean_usage_,',
       'punct__mean_usage_)', 'punct__mean_usage_-',
       'entities__mean_usage_PUNCEM', 'entities__mean_usage_SMILE',
       'pos__mean_usage_NUM', 'punct__mean_usage_!', 'punct__mean_usage_&',
       'entities__mean_usage_ADDRESS', 'entities__mean_usage_DATE',
       'entities__mean_usage_URL', 'punct__mean_usage_]',
       'punct__mean_usage_[', 'punct__mean_usage_;', 'punct__mean_usage_<',
       'punct__mean_usage_>', 'pos__mean_usage_INTJ', 'punct__mean_usage_/',
       'punct__mean_usage_*', 'punct__mean_usage__', 'punct__mean_usage_~',
       'entities__mean_usage_TAG', 'entities__mean_usage_EMAIL',
       'entities__mean_usage_PHONE', 'entities__mean_usage_POINTER', 'length'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
Index: 16091 entries, 0 to 16108
Data columns (total 81 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   age                                   16091 non-null  int64
 1   user_id                               16091 non-null  int64
 2   gender                                16091 non-null  str
 3   text                                  16091 non-null  str
 4   source_url                            6073 non-null   str
 5   text__symbols_length                  16091 non-null  float64
 6   text__sentences_count                 16091 non-null  int64
 7   text__long_sentences_proportion       16091 non-null  float64
 8   text__unpopular_words_proportion      16091 non-null  float64
 9   text__obscene_proportion              16091 non-null  float64
 10  text__rare_words_proportion           16091 non-null  float64
 11  text__type_token_ratio                16091 non-null  float64
 12  text__normalized_shannon_entropy      16091 non-null  float64
 13  text__mean_words_length               16091 non-null  float64
 14  text__long_words_proportion           16091 non-null  float64
 15  text__lexicon_size                    16091 non-null  float64
 16  text__lexical_diversity_per_sentence  16091 non-null  float64
 17  entities__mean_usage_QUOTE            12349 non-null  float64
 18  entities__mean_usage_NUMBER           10503 non-null  float64
 19  entities__mean_usage_MEAS             3313 non-null   float64
 20  entities__mean_usage_ENUM             5350 non-null   float64
 21  entities__mean_usage_FOREIGN          6396 non-null   float64
 22  entities__breadth_of_use_entities     16091 non-null  float64
 23  pos__index_of_formality               16091 non-null  float64
 24  pos__breadth_of_use_pos               16091 non-null  float64
 25  pos__pair_of_adv_per_sentence         16091 non-null  float64
 26  pos__mean_usage_NOUN                  16056 non-null  float64
 27  pos__mean_usage_PRON                  15909 non-null  float64
 28  pos__mean_usage_ADV                   15916 non-null  float64
 29  pos__mean_usage_ADP                   15979 non-null  float64
 30  pos__mean_usage_ADJ                   15978 non-null  float64
 31  pos__mean_usage_SCONJ                 15606 non-null  float64
 32  pos__mean_usage_AUX                   14252 non-null  float64
 33  pos__mean_usage_CCONJ                 15907 non-null  float64
 34  pos__mean_usage_VERB                  15978 non-null  float64
 35  pos__mean_usage_PROPN                 15418 non-null  float64
 36  pos__mean_usage_DET                   15826 non-null  float64
 37  pos__mean_usage_PART                  15827 non-null  float64
 38  pos__('ADJ-Pos', 'NOUN')              16024 non-null  float64
 39  pos__('PROPN', 'PUNCT')               16024 non-null  float64
 40  pos__('PUNCT', 'SCONJ')               16024 non-null  float64
 41  pos__('ADP', 'ADJ-Pos')               16024 non-null  float64
 42  pos__('ADP', 'PRON')                  16024 non-null  float64
 43  pos__('PUNCT', 'ADV')                 16024 non-null  float64
 44  pos__('PUNCT', 'PRON')                16024 non-null  float64
 45  pos__('ADJ-Pos', 'PUNCT')             16024 non-null  float64
 46  pos__('PUNCT', 'CCONJ')               16024 non-null  float64
 47  pos__index_of_formality_tuldava       16091 non-null  float64
 48  pos__index_of_formality_heylinger     16091 non-null  float64
 49  punct__breadth_of_use_puncts          16091 non-null  float64
 50  punct__mean_usage_:                   11281 non-null  float64
 51  punct__mean_usage_"                   1576 non-null   float64
 52  punct__mean_usage_.                   16039 non-null  float64
 53  punct__mean_usage_?                   8901 non-null   float64
 54  punct__mean_usage_(                   11092 non-null  float64
 55  punct__mean_usage_,                   15926 non-null  float64
 56  punct__mean_usage_)                   11495 non-null  float64
 57  punct__mean_usage_-                   11533 non-null  float64
 58  entities__mean_usage_PUNCEM           9004 non-null   float64
 59  entities__mean_usage_SMILE            4132 non-null   float64
 60  pos__mean_usage_NUM                   13730 non-null  float64
 61  punct__mean_usage_!                   8530 non-null   float64
 62  punct__mean_usage_&                   81 non-null     float64
 63  entities__mean_usage_ADDRESS          8994 non-null   float64
 64  entities__mean_usage_DATE             4690 non-null   float64
 65  entities__mean_usage_URL              2228 non-null   float64
 66  punct__mean_usage_]                   281 non-null    float64
 67  punct__mean_usage_[                   279 non-null    float64
 68  punct__mean_usage_;                   1809 non-null   float64
 69  punct__mean_usage_<                   133 non-null    float64
 70  punct__mean_usage_>                   190 non-null    float64
 71  pos__mean_usage_INTJ                  1465 non-null   float64
 72  punct__mean_usage_/                   1775 non-null   float64
 73  punct__mean_usage_*                   522 non-null    float64
 74  punct__mean_usage__                   161 non-null    float64
 75  punct__mean_usage_~                   22 non-null     float64
 76  entities__mean_usage_TAG              220 non-null    float64
 77  entities__mean_usage_EMAIL            156 non-null    float64
 78  entities__mean_usage_PHONE            52 non-null     float64
 79  entities__mean_usage_POINTER          1 non-null      float64
 80  length                                16091 non-null  int64
dtypes: float64(74), int64(4), str(3)
memory usage: 112.9 MB

In [9]:
with_na = df.columns[df.isna().sum() != 0].to_list()
display(with_na, len(with_na))

['source_url',
 'entities__mean_usage_QUOTE',
 'entities__mean_usage_NUMBER',
 'entities__mean_usage_MEAS',
 'entities__mean_usage_ENUM',
 'entities__mean_usage_FOREIGN',
 'pos__mean_usage_NOUN',
 'pos__mean_usage_PRON',
 'pos__mean_usage_ADV',
 'pos__mean_usage_ADP',
 'pos__mean_usage_ADJ',
 'pos__mean_usage_SCONJ',
 'pos__mean_usage_AUX',
 'pos__mean_usage_CCONJ',
 'pos__mean_usage_VERB',
 'pos__mean_usage_PROPN',
 'pos__mean_usage_DET',
 'pos__mean_usage_PART',
 "pos__('ADJ-Pos', 'NOUN')",
 "pos__('PROPN', 'PUNCT')",
 "pos__('PUNCT', 'SCONJ')",
 "pos__('ADP', 'ADJ-Pos')",
 "pos__('ADP', 'PRON')",
 "pos__('PUNCT', 'ADV')",
 "pos__('PUNCT', 'PRON')",
 "pos__('ADJ-Pos', 'PUNCT')",
 "pos__('PUNCT', 'CCONJ')",
 'punct__mean_usage_:',
 'punct__mean_usage_"',
 'punct__mean_usage_.',
 'punct__mean_usage_?',
 'punct__mean_usage_(',
 'punct__mean_usage_,',
 'punct__mean_usage_)',
 'punct__mean_usage_-',
 'entities__mean_usage_PUNCEM',
 'entities__mean_usage_SMILE',
 'pos__mean_usage_NUM',
 'punct__mean_usage_!',
 'punct__mean_usage_&',
 'entities__mean_usage_ADDRESS',
 'entities__mean_usage_DATE',
 'entities__mean_usage_URL',
 'punct__mean_usage_]',
 'punct__mean_usage_[',
 'punct__mean_usage_;',
 'punct__mean_usage_<',
 'punct__mean_usage_>',
 'pos__mean_usage_INTJ',
 'punct__mean_usage_/',
 'punct__mean_usage_*',
 'punct__mean_usage__',
 'punct__mean_usage_~',
 'entities__mean_usage_TAG',
 'entities__mean_usage_EMAIL',
 'entities__mean_usage_PHONE',
 'entities__mean_usage_POINTER']

57

## Установка значений по умолчанию

Для метрик значение `NaN` соответствует 0

In [10]:
zero_default_cols = with_na[:]
zero_default_cols.remove('source_url')

df[zero_default_cols] = df[zero_default_cols].fillna(0)

## Базовый осмотр статистических показателей

In [11]:
df.describe()

,age,user_id,text__symbols_length,text__sentences_count,text__long_sentences_proportion,text__unpopular_words_proportion,text__obscene_proportion,text__rare_words_proportion,text__type_token_ratio,text__normalized_shannon_entropy,...,pos__mean_usage_INTJ,punct__mean_usage_/,punct__mean_usage_*,punct__mean_usage__,punct__mean_usage_~,entities__mean_usage_TAG,entities__mean_usage_EMAIL,entities__mean_usage_PHONE,entities__mean_usage_POINTER,length
count,16091.000000,16091.000000,16091.000000,16091.000000,16091.000000,16091.000000,16091.000000,16091.000000,16091.000000,16091.000000,...,16091.000000,16091.000000,16091.000000,16091.000000,16091.000000,16091.000000,16091.000000,16091.000000,16091.000000,16091.000000
mean,37.046486,1158.062084,122.710267,41.730595,0.719022,0.354658,0.000140,0.510586,0.379068,1.341840,...,0.004607,0.009899,0.004441,0.011496,0.000074,0.002490,0.000488,0.000177,0.000005,3720.534460
std,10.576729,630.151302,234.211624,46.672893,0.165840,0.070444,0.001053,0.115301,0.109380,0.240626,...,0.050328,0.100404,0.054201,0.240071,0.004333,0.056748,0.007169,0.003781,0.000606,4065.225796
min,16.000000,1.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.072848,0.000000,0.449358,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
25%,29.000000,607.000000,69.078462,17.000000,0.631579,0.311547,0.000000,0.438070,0.311905,1.193174,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1479.000000
50%,36.000000,1181.000000,87.357143,27.000000,0.738095,0.346154,0.000000,0.511583,0.374286,1.316743,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2337.000000
75%,43.000000,1715.000000,112.479130,48.000000,0.833333,0.385887,0.000000,0.579597,0.437179,1.457551,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4147.500000
max,79.000000,2250.000000,6427.000000,590.000000,1.000000,1.000000,0.041667,1.000000,1.000000,4.680813,...,4.000000,8.500000,2.000000,20.615385,0.500000,4.166667,0.500000,0.166667,0.076923,32768.000000

## Удаляем наблюдения
Для обеспечения качества данных мы применяем последовательную фильтрацию, удаляя тексты с явными признаками ошибок разметки или выходящие за границы применимости нашего анализа.

1. Длина текста: от 300 до 10 000 символов (недостаточно информации либо превышение границ применимости)
2. Средняя длина предложения в словоформах: от 3 до 15 (ошибка токенизации либо неинформативный/избыточно сложный текст)
3. Средняя длина предложения в символах: не более 130 (аномально длинные предложения)
4. Среднее количество чисел: не более 2 на предложение
5. Среднее количество перечислений: не более 0.4 на предложение
6. Среднее количество единиц измерения: не более 0.4 на предложение
7. Среднее количество иностранных слов: не более 1 на предложение

In [12]:
df = df[
    (df['length'].between(300, 10000)) &
    (df['text__lexicon_size'].between(3, 15)) &
    (df['text__symbols_length'] <= 130) &
    (df['entities__mean_usage_NUMBER'] <= 2) &
    (df['entities__mean_usage_ENUM'] <= 0.4) &
    (df['entities__mean_usage_MEAS'] <= 0.4) &
    (df['entities__mean_usage_FOREIGN'] <= 1)
]

## Исправление наименования признаков
Некоторые методы анализа используют имя для своей работы. Наличие запятых, точек и прочего - помешает их работе

In [13]:
df.rename(columns={
    "pos__('ADJ-Pos', 'NOUN')": "pos__ADJPOS_NOUN",
    "pos__('PUNCT', 'SCONJ')": "pos__PUNCT_SCONJ",
    "pos__('ADP', 'ADJ-Pos')": "pos__ADP_ADJPOS",
    "pos__('ADP', 'PRON')": "pos__ADP_PRON",
    "pos__('PUNCT', 'ADV')": "pos__PUNCT_ADV",
    "pos__('ADJ-Pos', 'PUNCT')": "pos__ADJPOS_PUNCT",
    "pos__('PUNCT', 'CCONJ')": "pos__PUNCT_CCONJ",
    "pos__('PUNCT', 'PRON')": "pos__PUNCT_PRON",
    "pos__('PROPN', 'PUNCT')": "pos__PROPN_PUNCT",
    'punct__mean_usage_.': "punct__mean_usage_dot",
    'punct__mean_usage_,': "punct__mean_usage_comma",
    'punct__mean_usage_:': "punct__mean_usage_colon",
    'punct__mean_usage_"': "punct__mean_usage_quote",
    'punct__mean_usage_?': "punct__mean_usage_question",
    'punct__mean_usage_(': "punct__mean_usage_openparen",
    'punct__mean_usage_)': "punct__mean_usage_closeparen",
    'punct__mean_usage_-': "punct__mean_usage_hyphen",
    'punct__mean_usage_!': "punct__mean_usage_exclamation",
    'punct__mean_usage_&': "punct__mean_usage_ampersand",
    'punct__mean_usage_]': "punct__mean_usage_closebracket",
    'punct__mean_usage_[': "punct__mean_usage_openbracket",
    'punct__mean_usage_;': "punct__mean_usage_semicolon",
    'punct__mean_usage_<': "punct__mean_usage_lessthan",
    'punct__mean_usage_>': "punct__mean_usage_greaterthan",
    'punct__mean_usage_/': "punct__mean_usage_slash",
    'punct__mean_usage_*': "punct__mean_usage_asterisk",
    'punct__mean_usage__': "punct__mean_usage_underscore",
    'punct__mean_usage_~': "punct__mean_usage_tilde"
}, inplace=True)

## Сохраняем данные

In [14]:
print(f"Исходный набор данных похудел на {start_size - len(df)} наблюдений")

Исходный набор данных похудел на 4077 наблюдений

In [15]:
from pathlib import Path
output_dir = Path("../data/processed").resolve()
output_dir.mkdir(parents=True, exist_ok=True)
output_path = output_dir / "filtered.parquet"
df.to_parquet(output_path)